version: '3.8'
services:
  db:
    image: postgres
    restart: no
    container_name: mce-database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
volumes:
  dbdata: