export interface TestModel {
    id: string,
    name: string,
    password: string,
    time: string,
    easy_question: number,
    medium_question: number,
    difficult_question: number,
    show_correct_answer: string,
    show_mark: string,
    submit_when_switch_tab: string,
    user_id: string,
    subject_id: string,
    semester_id: string,
    chapters: string,
    swap_question: string,
    swap_answer: string,
    total_mark: string,
    createdAt: string,
    updatedAt: string,
    questions: QuestionModel[],
}

export interface QuestionModel {
    id: number,
    question: string,
    level: string,
    answer_a: string,
    answer_b: string,
    answer_c: string,
    answer_d: string,
    correct_answer: string,
    user_create: string,
    chapter_name: string,
    image: any,
    is_admin_create: number,
    chapter_id: number,
    answer: string,
}

export interface QuestionResultModel {
    id: number,
    correct_answer: string,
    answer: string,
}